### ISSUE TITLE
Doesn't work with German numbers?

### ISSUE THREAD

**Issue by treysis** [MarcoBuster/haveibeenfacebooked-frontend#2]
I know a German number that is contained in the leak, but your site reports it is not.

**Comment by kennyluk** [comment]
Same with Canada

**Comment by MarcoBuster** [comment]
We're rebuilding our database with PostgreSQL and we're hashing the phone numbers. During the process, we're adding the missing countries. Thank you for your contribution, I'll keep the issue open until we fixed it.

**Comment by MarcoBuster** [comment]
@treysis @kennyluk is it fixed now?

**Comment by treysis** [comment]
Yes. Thx!
