### ISSUE TITLE
Required phone number format is unclear

### ISSUE THREAD

**Issue by bokub** [MarcoBuster/haveibeenfacebooked-frontend#7]
Hi,

It is very unclear whether I should include the '0' of my phone number or not.

Maybe you could add a hint on the input, or some validation?

![image](https://user-images.githubusercontent.com/17952318/113717209-ad113880-96eb-11eb-80f9-d05d92d49d0d.png)
![image](https://user-images.githubusercontent.com/17952318/113717183-a71b5780-96eb-11eb-9512-8409be75ba5f.png)

**Comment by MarcoBuster** [comment]
Why would you include the '0'? Is this a regional thing?

**Comment by bokub** [comment]
If I want to call a french number, both the following work:

- 06.11.22.33.44
- +336.11.22.33.44
The indicator (+33) replaces the 0

My question is: should I include this '0' in the input, or not ?

**Comment by MarcoBuster** [comment]
Use the international format. When in doubt, check both.

**Comment by bokub** [comment]
All right, thanks
